# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a6911c944fd1664b1478a875a8a3fd6e504b9012bde20ac2d42017d8393c00e67a5e8741813148b6ecf89ae68d10d7830043551e372c0f09d15a87d3984fbdf

test:
  secret_key_base: d1db6da58b176bb2fbc7b40a1a1cde828a4c2f069cd2188a20b1192d83510c20a916cf09bd5284d2d1c3d495bdbe6d0f3f3a4439d8b4aa96748aa862bd1f917b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
